### ISSUE TITLE
Unhandled exception when attempting to retrieve commit.

### ISSUE THREAD

**Issue by Nuno-Mota** [aimhubio/aim#2742]
## 🐛 Bug

Hi.

I'm getting an issue with the try block associated with this line (in the version I have installed):
https://github.com/aimhubio/aim/blob/416a599ef1c6e80ec08d046a24f49255aa604e98/aim/ext/utils.py#L59
(in the `main` branch):
https://github.com/aimhubio/aim/blob/f469779312ab0e01c0a9241d2b5cecf55b97910a/src/aim/ext/system_info/utils.py#L59

Essentially, if `'commit'` is not part of `results`, the `get()` method will return `None`, which doesn't have a `split()` method. This means that an `AttributeError` is raised, instead of a `ValueError`, which will not be caught and will make the program crash.

### To reproduce

It seems like `aim init` is not initiating a `git` repository and, hence, the corresponding subprocess command to retrieve `'commit'` will fail.
I'm not sure what's causing a `git` repository to not be initiated in the first place.
However, I can track values and visualize them via the web interface (when using the fix below).

### Expected behavior

The following try block would handle the issue:
```python
try:
	commit_hash, commit_timestamp, commit_author = results['commit'].split('/')
except KeyError:
	commit_hash = commit_timestamp = commit_author = None
```

### Environment

- Aim Version: 3.17.4
- Python version: 3.10.8
- pip version: 23.1.2
- OS: Archlinux

**Comment by anigmetov** [comment]
If I understand correctly, `aim init` is not supposed to initialize a git repo. The purpose of utils.get_git_info() is to get the information about the git repository in which the script being run lives. I (user) create a git repo for my python code, instrument it with aim, and aim records, for each experiment, which git commit in my repository it was that produced these particular results.

I have just discovered a funny 'bug' with the same error message, but in my case the cause of the problem was that the server on which I was running my code had an old git, version 1.8, and it does not support `--date=iso-strict` format, only `--date=iso`; after loading the module with git 2.36.1 the problem was solved.

**Comment by Nuno-Mota** [comment]
> If I understand correctly, `aim init` is not supposed to initialize a git repo. The purpose of utils.get_git_info() is to get the information about the git repository in which the script being run lives. I (user) create a git repo for my python code, instrument it with aim, and aim records, for each experiment, which git commit in my repository it was that produced these particular results.

Ah, that might indeed be the case!
Unfortunately, at the time I wasn't able to delve too deeply into what this function was being used for, due to lack of time.
In any case, the error itself still exists.
As I was working on a newly initiated git repository, it still had no commits made to it, which would explain the 'commit' key being missing from `results`.

**Comment by mihran113** [comment]
Hey @Nuno-Mota! Thanks a lot for report. There's a patch release planned in the upcoming next 2 days, I will make sure to include the fix in that. 

@anigmetov thanks for the additional info, but anyways this case should be handled at our end.

**Comment by mihran113** [comment]
Closing this as the fix was shipped with `aim v3.17.5`.
